/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.qljl.tmm;

public final class R {
    public static final class anim {
        public static final int ddddddddddd=0x7f040000;
        public static final int fade_in=0x7f040001;
        public static final int fade_out=0x7f040002;
        public static final int left_in=0x7f040003;
        public static final int left_out=0x7f040004;
        public static final int pophidden_anim=0x7f040005;
        public static final int popshow_anim=0x7f040006;
        public static final int right_in=0x7f040007;
        public static final int right_out=0x7f040008;
        public static final int translate_anim=0x7f040009;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int tb_munion_item_force=0x7f090000;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 
         */
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
    }
    public static final class drawable {
        public static final int back=0x7f020000;
        public static final int butten_pressed=0x7f020001;
        public static final int butten_unpress=0x7f020002;
        public static final int dark_dot=0x7f020003;
        public static final int details=0x7f020004;
        public static final int dot=0x7f020005;
        public static final int ic_focus=0x7f020006;
        public static final int ic_focus_select=0x7f020007;
        public static final int ic_launcher=0x7f020008;
        public static final int ic_select_bg=0x7f020009;
        public static final int icon=0x7f02000a;
        public static final int load=0x7f02000b;
        public static final int tb_munion_icon=0x7f02000c;
        public static final int tb_munion_item_selector=0x7f02000d;
        public static final int umeng_common_gradient_green=0x7f02000e;
        public static final int umeng_common_gradient_orange=0x7f02000f;
        public static final int umeng_common_gradient_red=0x7f020010;
        public static final int umeng_update_btn_check_off_focused_holo_light=0x7f020011;
        public static final int umeng_update_btn_check_off_holo_light=0x7f020012;
        public static final int umeng_update_btn_check_off_pressed_holo_light=0x7f020013;
        public static final int umeng_update_btn_check_on_focused_holo_light=0x7f020014;
        public static final int umeng_update_btn_check_on_holo_light=0x7f020015;
        public static final int umeng_update_btn_check_on_pressed_holo_light=0x7f020016;
        public static final int umeng_update_button_cancel_bg_focused=0x7f020017;
        public static final int umeng_update_button_cancel_bg_normal=0x7f020018;
        public static final int umeng_update_button_cancel_bg_selector=0x7f020019;
        public static final int umeng_update_button_cancel_bg_tap=0x7f02001a;
        public static final int umeng_update_button_check_selector=0x7f02001b;
        public static final int umeng_update_button_close_bg_selector=0x7f02001c;
        public static final int umeng_update_button_ok_bg_focused=0x7f02001d;
        public static final int umeng_update_button_ok_bg_normal=0x7f02001e;
        public static final int umeng_update_button_ok_bg_selector=0x7f02001f;
        public static final int umeng_update_button_ok_bg_tap=0x7f020020;
        public static final int umeng_update_close_bg_normal=0x7f020021;
        public static final int umeng_update_close_bg_tap=0x7f020022;
        public static final int umeng_update_dialog_bg=0x7f020023;
        public static final int umeng_update_title_bg=0x7f020024;
        public static final int umeng_update_wifi_disable=0x7f020025;
        public static final int whats_new_start_btn=0x7f020026;
        public static final int white_dot=0x7f020027;
        public static final int yw_1222=0x7f020028;
    }
    public static final class id {
        public static final int cameraPreview=0x7f0b0014;
        public static final int imageView=0x7f0b0000;
        public static final int progressBar=0x7f0b0013;
        public static final int scanText=0x7f0b0015;
        public static final int umeng_common_icon_view=0x7f0b0002;
        public static final int umeng_common_notification=0x7f0b0006;
        public static final int umeng_common_notification_controller=0x7f0b0003;
        public static final int umeng_common_progress_bar=0x7f0b0009;
        public static final int umeng_common_progress_text=0x7f0b0008;
        public static final int umeng_common_rich_notification_cancel=0x7f0b0005;
        public static final int umeng_common_rich_notification_continue=0x7f0b0004;
        public static final int umeng_common_title=0x7f0b0007;
        public static final int umeng_update_content=0x7f0b000d;
        public static final int umeng_update_frame=0x7f0b000a;
        public static final int umeng_update_id_cancel=0x7f0b0010;
        public static final int umeng_update_id_check=0x7f0b000e;
        public static final int umeng_update_id_close=0x7f0b000c;
        public static final int umeng_update_id_ignore=0x7f0b0011;
        public static final int umeng_update_id_ok=0x7f0b000f;
        public static final int umeng_update_wifi_indicator=0x7f0b000b;
        public static final int update_progress=0x7f0b0001;
        public static final int webView=0x7f0b0012;
    }
    public static final class layout {
        public static final int loading=0x7f030000;
        public static final int softupdate_progress=0x7f030001;
        public static final int umeng_common_download_notification=0x7f030002;
        public static final int umeng_update_dialog=0x7f030003;
        public static final int webview=0x7f030004;
        public static final int zbar_capture=0x7f030005;
    }
    public static final class menu {
        public static final int main=0x7f0a0000;
    }
    public static final class raw {
        public static final int beep=0x7f050000;
    }
    public static final class string {
        public static final int UMAppUpdate=0x7f070021;
        public static final int UMBreak_Network=0x7f070019;
        public static final int UMDialog_InstallAPK=0x7f070025;
        public static final int UMGprsCondition=0x7f07001f;
        public static final int UMIgnore=0x7f070023;
        public static final int UMNewVersion=0x7f07001b;
        public static final int UMNotNow=0x7f070022;
        public static final int UMTargetSize=0x7f07001e;
        public static final int UMToast_IsUpdating=0x7f070024;
        public static final int UMUpdateCheck=0x7f070026;
        public static final int UMUpdateContent=0x7f07001c;
        public static final int UMUpdateNow=0x7f070020;
        public static final int UMUpdateSize=0x7f07001d;
        public static final int UMUpdateTitle=0x7f07001a;
        public static final int action_settings=0x7f070001;
        public static final int app_name=0x7f070000;
        public static final int soft_update_cancel=0x7f070008;
        public static final int soft_update_info=0x7f070004;
        public static final int soft_update_later=0x7f070006;
        /**  升级 
 升级 
         */
        public static final int soft_update_no=0x7f070002;
        public static final int soft_update_title=0x7f070003;
        public static final int soft_update_updatebtn=0x7f070005;
        public static final int soft_updating=0x7f070007;
        public static final int tb_munion_tip_download_prefix=0x7f070009;
        public static final int umeng_common_action_cancel=0x7f07000e;
        public static final int umeng_common_action_continue=0x7f07000d;
        public static final int umeng_common_action_info_exist=0x7f07000a;
        public static final int umeng_common_action_pause=0x7f07000c;
        public static final int umeng_common_download_failed=0x7f070014;
        public static final int umeng_common_download_finish=0x7f070015;
        public static final int umeng_common_download_notification_prefix=0x7f07000f;
        public static final int umeng_common_icon=0x7f070018;
        public static final int umeng_common_info_interrupt=0x7f07000b;
        public static final int umeng_common_network_break_alert=0x7f070013;
        public static final int umeng_common_patch_finish=0x7f070016;
        public static final int umeng_common_pause_notification_prefix=0x7f070010;
        public static final int umeng_common_silent_download_finish=0x7f070017;
        public static final int umeng_common_start_download_notification=0x7f070011;
        public static final int umeng_common_start_patch_notification=0x7f070012;
    }
    public static final class style {
        /**  Popup动画 
         */
        public static final int AnimationPreview=0x7f080002;
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f080000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f080001;
        /**  popwidnow 显示消失动画
 指定消失的动画xml  
         */
        public static final int mypopwindow_anim_style=0x7f080003;
    }
}
